### ISSUE TITLE
borderRadius doesn't work

### ISSUE THREAD

**Issue by smart-mickey** [oblador/react-native-image-progress#61]
I tried to implement for avatar image, but the borderRadius props doesn't work to the image.

**Comment by skv-headless** [comment]
Here how I did this
```js
import { createImageProgress } from 'react-native-image-progress';

const ImageComponent = (props) => {
  const newProps = {...props, overlayColor: 'white', borderRadius: 8 };
  return <Image {...newProps} />;
}

const ImageProgress = createImageProgress(ImageComponent);
```

**Comment by joncursi** [comment]
I'm running into a similar issue. It's no surprise that [react-native > Android has issues with specifying radii on images](https://github.com/facebook/react-native/issues/3198), but I've found that in my Avatar component, using the default `Image` export from react-native core yields the result I want:

![screen shot 2017-09-21 at 8 23 09 pm](https://user-images.githubusercontent.com/4974609/30724385-8e6076e8-9f0b-11e7-8746-7bbf80de4684.png)

whereas using the `Image` component from this library (with otherwise identical code) does not:

![screen shot 2017-09-21 at 8 23 57 pm](https://user-images.githubusercontent.com/4974609/30724403-9d163cb8-9f0b-11e7-8559-10393505296c.png)

I'm not sure what causes the square corners to creep back in. I suspect it's the `absoluteFill` being applied to the Image that causes it to break out of it's container: https://github.com/oblador/react-native-image-progress/blob/master/index.js#L203

**Comment by fessi786** [comment]
Change in the module **index.js** file.
Line _number 204_
Change _Style={StyleSheet.absolutefill} to style={this.props.style}_
these are the image style you pass in your app where you are using Image.
example:
<Image
                  source = {{uri: this.props.employee.employeeImage}}
                  indicator={Progress.Circle}
                  indicatorProps={{
                    size: 40,
                    color: apptheme,
                    unfilledColor: 'rgba(200, 200, 200, 0.2)'
                  }}
                  **style={styles.thumbnail}**
                  />

**Comment by sachinwak** [comment]
@fessi786   thank you it works!

**Comment by djalmajr** [comment]
I did this:

![image](https://user-images.githubusercontent.com/1858147/32566670-678a8fac-c497-11e7-8cf2-2965ace0da8a.png)

and I use like this:

![image](https://user-images.githubusercontent.com/1858147/32566699-7e50d11a-c497-11e7-8ffe-8485b23b3bf4.png)

**Comment by oblador** [comment]
Hi, this can be solved by the `imageStyle` prop released in [1.1.0](https://github.com/oblador/react-native-image-progress/releases/tag/v1.1.0).

**Comment by lifeiscontent** [comment]
@oblador I'm getting an issue saying that imageStyle prop is expecting a number vs an object.

**Comment by smart-mickey** [comment]
I used react-native-image-progress@1.0.1 and it works great by the following code.

const style={
  ...
  width: 60,
  height: 60,
  borderRadius: 30,
  overflow: 'hidden',
  ...
}

<Image source={{uri: imageURL}}  indicator={ProgressBar} style={style} />

**Comment by bridgewaterlabs** [comment]
funny thing is that borderRadius works fine but borderTopLeftRadius and other corner radiuses are not
overflow:  'hidden' works on main style with the corner radiuses 

like this 
`style={{
                  flex: 1,
                  borderTopLeftRadius: 20,
                  borderTopRightRadius: 20,
                  overflow: 'hidden'
                }}`

**Comment by eddskt** [comment]
> I used react-native-image-progress@1.1.0 and it works great by the following code.
> 
> <Image
> source = {{uri: ImageURL}}
> indicator={Progress.Circle}
> imageStyle={{
> width: 60,
> height: 60,
> borderRadius: 30,
> overflow: 'hidden',
> }}
> />

Ohhh very Nice, works for me, i had forgotten the 'overflow' property

**Comment by IlyassElharrar** [comment]
@smart-mickey 
solved , thanks
